eureka:
  client:
    serviceUrl:
      defaultZone: ${EUREKA_SERVER_URI:http://localhost:8761/eureka/}
#      EUREKA_URI: http://eureka-server:8761/eureka/

ribbon:
  eureka:
    enabled: true

zuul:
  routes:
    gateway:
      path: /gateway/**
      serviceId: gateway-service
    notifications:
      path: /notification-service/**
      serviceId: notification-service
    config-server:
      path: /config-server/**
      serviceId: config-server
    eureka-server:
      path: /eureka/**
      serviceId: eureka-server
    monitor-service:
      path: /monitor-service/**
      serviceId: monitor-service