# !!! OKAZUJE SIE ZE TO W OGOLE NIE JEST POTRZEBNE JESLI EUREKA JEST NA DEFAULTOWYCH PARAMSACH
#eureka:
#  instance:
#    hostname: config-server
#  client:
#    registerWithEureka: true
#    fetchRegistry: true
#    serviceUrl:
#      defaultZone: http://localhost:8761/eureka/

management:
  endpoints:
    web:
      exposure:
        include: '*'

spring:
  cloud:
    config:
      discovery:
        enabled: true